In [1]:
from syft.util import get_root_data_path
from six.moves import urllib
opener = urllib.request.build_opener()
opener.addheaders = [("User-agent", "Mozilla/5.0")]
urllib.request.install_opener(opener)
import torchvision
torchvision.datasets.MNIST(get_root_data_path(), train=True, download=True)
torchvision.datasets.MNIST(get_root_data_path(), train=False, download=True)

Dataset MNIST
    Number of datapoints: 10000
    Root location: /home/tk/.syft/data
    Split: Test

In [1]:
import syft as sy
duet = sy.launch_duet(loopback=True)

🎤  🎸  ♪♪♪ Starting Duet ♫♫♫  🎻  🎹

♫♫♫ > DISCLAIMER: Duet is an experimental feature currently in beta.
♫♫♫ > Use at your own risk.


    > ❤️ Love Duet? Please consider supporting our community!
    > https://github.com/sponsors/OpenMined

♫♫♫ > Punching through firewall to OpenGrid Network Node at:
♫♫♫ > http://ec2-18-218-7-180.us-east-2.compute.amazonaws.com:5000
♫♫♫ >
♫♫♫ > ...waiting for response from OpenGrid Network... 
♫♫♫ > DONE!

♫♫♫ > STEP 1: Send the following code to your Duet Partner!

import syft as sy
duet = sy.join_duet(loopback=True)

♫♫♫ > Connecting...


/home/tk/Desktop/Studia/masters/env/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py:211: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  _openssl_assert(lib.SSL_CTX_use_certificate(ctx, self._cert._x509) == 1)  # type: ignore
/home/tk/Desktop/Studia/masters/env/lib/python3.10/site-packages/aiortc/rtcdtlstransport.py:186: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  value=certificate_digest(self._cert._x509),  # type: ignore



♫♫♫ > CONNECTED!



In [3]:
duet.store.pandas

Empty DataFrame
Columns: []
Index: []

In [8]:
data_ptr = duet.store[0]

In [12]:
print(data_ptr.float().mean().get())

tensor(46.8333)


In [7]:
import torch as th

In [15]:
test_data = th.tensor([1,2,3,4,5,6])
test_data.tag("test")
test_data.describe("Count to 6")

tensor([1, 2, 3, 4, 5, 6])

In [16]:
age_data_pointer = test_data.send(duet,pointable=True)

[2022-09-04T21:12:17.196214+0200][CRITICAL][logger]][11304] You do not have permission to .get() Object with ID: <UID: 5e1e8098692e46d0a17e0eff0e85a044>Please submit a request.
[2022-09-04T21:12:17.197130+0200][CRITICAL][logger]][11304] You do not have permission to .get() Object with ID: <UID: 5e1e8098692e46d0a17e0eff0e85a044>Please submit a request.
[2022-09-04T21:12:50.189823+0200][CRITICAL][logger]][11304] You do not have permission to .get() Object with ID: <UID: 3fe03ddf509d434c8cfd2b312f6cfbe3>Please submit a request.
[2022-09-04T21:12:50.190607+0200][CRITICAL][logger]][11304] You do not have permission to .get() Object with ID: <UID: 3fe03ddf509d434c8cfd2b312f6cfbe3>Please submit a request.


In [21]:
duet.requests.pandas

Requested Object's tags                                             Reason  \
0                  [test]  I want to access the test data to perform a si...   

                                Request ID  \
0  <UID: d75b28a6846d4cdc9fd143254ec0f0b0>   

                     Requested Object's ID Requested Object's type  
0  <UID: feb54e10f132405683e259213b8a6f63>  <class 'torch.Tensor'>

In [22]:
duet.requests[0].request_description

'I want to access the test data to perform a simple analysis'

In [24]:
#duet.requests[0].deny()
duet.requests[0].accept()

In [12]:
duet.requests.add_handler(action="accept",tags=["access"])

In [8]:
test_data = th.tensor([11,12,13,14,15,16])
test_data.tag("access")
test_data.describe("11-16")
age_data_pointer = test_data.send(duet,pointable=True)

tensor([11, 12, 13, 14, 15, 16])

In [9]:
age_data_pointer = test_data.send(duet,pointable=True)

In [10]:
duet.store.pandas

ID      Tags Description  \
0  <UID: eae87ea9a5ae4fd79834f4b57a71e060>  [access]       11-16   

              object_type  
0  <class 'torch.Tensor'>

[2022-09-05T19:14:51.184581+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 12a8c198f15c4b5e822851daa466f59f>Please submit a request.
[2022-09-05T19:14:51.185886+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 12a8c198f15c4b5e822851daa466f59f>Please submit a request.
[2022-09-05T19:15:13.613967+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 7690f07fbb05473d8730f547cce6b83d>Please submit a request.
[2022-09-05T19:15:13.614540+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 7690f07fbb05473d8730f547cce6b83d>Please submit a request.


In [13]:
duet.requests.pandas

Empty DataFrame
Columns: []
Index: []

In [14]:
test_data = th.tensor([11,12,13,14,15,16])
test_data.tag("deny")
test_data.describe("11-16")
age_data_pointer = test_data.send(duet,pointable=True)

[2022-09-05T19:20:44.827959+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 046391c60abe4b3c879ea26984a25e74>Please submit a request.
[2022-09-05T19:20:44.828955+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 046391c60abe4b3c879ea26984a25e74>Please submit a request.
[2022-09-05T19:20:50.615470+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 7296b64404484a7e9b3ee77d7fba12f4>Please submit a request.
[2022-09-05T19:20:50.616430+0200][CRITICAL][logger]][37462] You do not have permission to .get() Object with ID: <UID: 7296b64404484a7e9b3ee77d7fba12f4>Please submit a request.


In [15]:
test_data = th.tensor([5,6,7,8,9])
test_data.tag("access")
test_data.describe("5-9")
age_data_pointer = test_data.send(duet,pointable=True)

In [17]:
duet.store.pandas

ID      Tags Description  \
0  <UID: 3a5dc1b9106d4daca6a6aca14d278c90>    [deny]       11-16   
1  <UID: 0bf28dd231ac4fd5b6ac70fd14b70029>  [access]         5-9   

              object_type  
0  <class 'torch.Tensor'>  
1  <class 'torch.Tensor'>

### IRIS Example

In [2]:
from sklearn import datasets
import torch as th

In [3]:
iris = datasets.load_iris()
x, y = iris.data, iris.target

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
th_x = th.FloatTensor(x)
th_y = th.FloatTensor(y)

In [6]:
th_x.tag("iris-data")
th_x.describe("The cms of of septal len, width, prental len, width")

th_y.tag("iris-target")
th_y.describe("Iris labels")

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2.])

In [7]:
th_x.send(duet, pointable=True)
th_y.send(duet, pointable=True)

In [10]:
duet.requests.add_handler(action="accept")

In [11]:
duet.store.pandas

ID  \
0   <UID: 6f8a7ebaa5664e37afb0e3ff1332852f>   
1   <UID: 43a59b04ac494632a19e9a91452a3045>   
2   <UID: 2b60c2d29b8c49ad8915baa0a18ee078>   
3   <UID: 618c9a55bab44224b075065ce968a63e>   
4   <UID: 8ddfbfd39b9e4b03b345c24a361403bf>   
5   <UID: a4b3b218979743308201139b72b7c673>   
6   <UID: 38cb9b6cada642cc9feb29fa9af005b1>   
7   <UID: be52bae927164db390fa978252eac46f>   
8   <UID: 230c1cefdcac49cabd50bb7e354dd9c5>   
9   <UID: 4af3acf8411b438da5a0fb2e935aa302>   
10  <UID: 7923317b275c4928bfd79cedb22c44f2>   
11  <UID: 6e4f090b9a684b6b8c3aefce5f745a8c>   
12  <UID: 9aa1ec49f05e4f2ba04f18aa6c440812>   
13  <UID: 41fc09b96b3d44e7b0fbb1d79479723d>   
14  <UID: 06cf4e58c9c849c4bfc88ea142816682>   
15  <UID: 4540b74dd675402a8972f29478ab66df>   
16  <UID: a4f790f402184b3dbae9cf35ddc21650>   
17  <UID: 717d9ee56c0648cfaf9a1f3772d0f63e>   
18  <UID: 591212fbc4054f66b812f00f86ac2cae>   
19  <UID: 2fb56d3622c64e0cb50df065eface219>   
20  <UID: d1899a2b27ad449bb607fe6bb49f23ec>   

                                                 Tags  \
0                                         [iris-data]   
1                                       [iris-target]   
2                                                  []   
3                                                  []   
4                                                  []   
5                                                  []   
6                                                  []   
7                                                  []   
8                                                  []   
9                                                  []   
10                                                 []   
11                                                 []   
12                                                 []   
13  [iris-data, __call__, relu, __call__, relu, __...   
14  [iris-data, __call__, relu, __call__, relu, __...   
15  [iris-data, __call__, relu, __call__, relu, __...   
16  [iris-data, __call__, relu, __call__, relu, __...   
17  [iris-data, __call__, relu, __call__, relu, __...   
18  [iris-data, __call__, relu, __call__, relu, __...   
19  [iris-data, __call__, relu, __call__, relu, __...   
20  [iris-data, __call__, relu, __call__, relu, __...   

                                          Description  \
0   The cms of of septal len, width, prental len, ...   
1                                         Iris labels   
2                                                       
3                                                       
4                                                       
5                                                       
6                                                       
7                                                       
8                                                       
9                                                       
10                                                      
11                                                      
12                                                      
13                                                      
14                                                      
15                                                      
16                                                      
17                                                      
18                                                      
19                                                      
20                                                      

                                 object_type  
0                     <class 'torch.Tensor'>  
1                     <class 'torch.Tensor'>  
2   <class 'torch.nn.modules.module.Module'>  
3   <class 'torch.nn.modules.linear.Linear'>  
4   <class 'torch.nn.modules.linear.Linear'>  
5   <class 'torch.nn.modules.linear.Linear'>  
6            <class 'torch.optim.adam.Adam'>  
7        <class 'syft.lib.python.list.List'>  
8            <class 'torch.optim.adam.Adam'>  
9   <class 'torch.nn.modul

[2022-09-07T15:49:23.628872+0200][CRITICAL][logger]][45356] You do not have permission to .get() Object with ID: <UID: 6f8a7ebaa5664e37afb0e3ff1332852f>Please submit a request.
[2022-09-07T15:49:23.630760+0200][CRITICAL][logger]][45356] You do not have permission to .get() Object with ID: <UID: 6f8a7ebaa5664e37afb0e3ff1332852f>Please submit a request.
