In [23]:
import os
import sys
module_path = os.path.abspath(os.path.join('fede'))
if module_path not in sys.path:
    sys.path.append(module_path)
# import pandas as pd
from client import Client
from supported_modles import Supported_modles
import utils
from fedavg import Fedavg
from sklearn.utils.class_weight import compute_sample_weight
import numpy as np
import random

In [24]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [25]:
selected_model = Supported_modles.NN_classifier
client1 = Client("node1","0.0.0.0", 5000, selected_model, "api")
dataset = client1.load_data('data/xaa.csv', True)
client1.preprocess_data(dataset, True)
client1.prep_data()
test_x = client1.x
test_y = client1.y



Creating node1.


In [37]:
client1.login_api()
client1.init_empty_model()
client1.get_global_model()
client1.model.fc3.bias.data

print('----------------------------------------')
print(client1.test_model_f1(test_y,test_x))
print('----------------------------------------')

loged in succesfully!
----------------------------------------
0.6377155369035672
----------------------------------------


In [ ]:
0, 59, 72, 0,71 0.617, 0.81 0.601 0.852 0.58 0.70 0.717 0.734

In [4]:
selected_model = Supported_modles.NN_classifier

In [5]:
clients = utils.set_data_mock(selected_model, True)

Creating node1.
Creating node2.
Creating node3.
Creating node4.


In [ ]:
client1.model = fedavg.model
print('----------------------------------------')
print(client1.test_model_f1(test_y,test_x))
print('----------------------------------------')


In [5]:
# for client in clients:
#     client.init_empty_model(epochs=50)
#     client.train_model(epochs=50)
#     score = client.test_model_f1()
#     print(score)

In [24]:
for client in clients:
    client.init_empty_model(epochs=50)
    data = client.fed_avg_prepare_data(epochs=10)
    score = client.test_model_f1()
    print(score)

0.9328640431347587
0.8814088754847049
0.9372570794003332


In [50]:
clients[0].login_api()
data = clients[0].fed_avg_prepare_data(epochs=10)
clients[0].send_local_model(data)

loged in succesfully!
200
{"message":"Model created"}



In [51]:
clients[1].login_api()
data = clients[1].fed_avg_prepare_data(epochs=10)
clients[1].send_local_model(data)

loged in succesfully!
200
{"message":"Model created"}



In [52]:
clients[2].login_api()
data = clients[2].fed_avg_prepare_data(epochs=10)
clients[2].send_local_model(data)

loged in succesfully!
200
{"message":"Model created"}



In [54]:
for client in clients:
    client.login_api()
    client.get_global_model()
    score = client.test_model_f1()
    print(score)
    print(client.model.fc3.bias)

loged in succesfully!
0.7945866475666302
Parameter containing:
tensor([-9.0175e-05,  9.0175e-05], requires_grad=True)
loged in succesfully!
0.6597278543750563
Parameter containing:
tensor([-9.0175e-05,  9.0175e-05], requires_grad=True)
loged in succesfully!
0.9333333333333333
Parameter containing:
tensor([-9.0175e-05,  9.0175e-05], requires_grad=True)
